### ISSUE TITLE
App froze after present RMActionController on iOS 8

### ISSUE THREAD

**Issue by tiepvuvan** [CooperRS/RMActionController#11]
on iOS 8, present RMActionController have a strange animation, and after animation, app froze
here is preview
https://vid.me/Yrpe

Sample code:

``` swift
if let dateSelectionVC = RMDateSelectionViewController(style: .Default, selectAction: RMAction(title: "Select".localizedString, style: .Default, andHandler: { [weak sender] (controller: RMActionController!) in

  let date = (controller.contentView as! UIDatePicker).date
  sender?.setOrderDate(date)

}), andCancelAction: RMAction(title: "Cancel".localizedString, style: .Cancel, andHandler: { _ in

})) {
   dateSelectionVC.datePicker.datePickerMode = .Date
   dateSelectionVC.disableBlurEffects = true
   dateSelectionVC.disableBouncingEffects = true
   dateSelectionVC.datePicker?.date = date
   dateSelectionVC.datePicker?.maximumDate = NSDate()

   presentViewController(dateSelectionVC, animated: true, completion: nil)
}
```

**Comment by CooperRS** [comment]
Hey!

this seems somehow being related to the keyboard being presented just before the RMDateSelectionViewController is presented.

Can you provide me a demo project with the bug?

Best regards,
Roland

**Comment by Krushnapal248** [comment]
I am facing exactly the same scenario. I am not using any keyboard as mentioned by Roland, can be a cause. So could be please verify the issue? I am stuck here for a long time. I also debug RMDateSelectionViewController and RMActionController, but no luck.

**Comment by CooperRS** [comment]
@Krushnapal248 Can you provide me a demo project?

**Comment by CooperRS** [comment]
Is this issue still present? Please reopen if this is the case.
