### ISSUE TITLE
Is possible add new action like UIAlertController?

### ISSUE THREAD

**Issue by alfio86** [CooperRS/RMActionController#13]
Hello,
In iOS  with UIAlertController you can set many action with:
[alert addAction:action]; 
[alert addAction:action2];
[alert addAction:action3];
Etc...
Here apparently only two action (one is cancel). Is there a way to have only a list of buttons with this cool design?

**Comment by CooperRS** [comment]
Hi,

yes, this is definitely possible. You may take a look at the Tests to see an example (for example [this one](https://github.com/CooperRS/RMActionController/blob/master/RMActionController-Demo-Tests/RMCustomViewActionControllerTests.m)).

Just call addAction: multiple times and you can add as many actions as you want.

Best regards,
Roland
