### ISSUE TITLE
Dismiss (close) controller programmatically 

### ISSUE THREAD

**Issue by souzainf3** [CooperRS/RMActionController#16]
To close the controller is required user interaction. I recommend a public accessor type "dismissController" when if that necessary give the programmer can remove the viewing screen

**Comment by CooperRS** [comment]
Hi there,

Actually ```RMActionController``` is just a ```UIViewController``` and you can dismiss it like any other modally pushed view controller using ```dismissViewControllerAnimated:completion:```.

Best regards,
Roland
