### ISSUE TITLE
Swift version

### ISSUE THREAD

**Issue by gpongelli** [CooperRS/RMActionController#2]
Hi,
I've found this repository and it's really cool.
Have you any plan to convert this code to Swift ?

Thank you!

**Comment by CooperRS** [comment]
Hi, I think there is no need for converting the code to swift. You can use the control in swift projects, too. Either by using a bridging header or by using frameworks (for example with cocoapods).

**Comment by gpongelli** [comment]
I know it's possible using bridging header but I tend to avoid ObjectiveC in my project.
