### ISSUE TITLE
iPhone: black backgroundcolor on portrait orientation

### ISSUE THREAD

**Issue by bender75** [CooperRS/RMActionController#23]
Hello,

thank you for this great classes. I want to use RMActionController for an universal app and hope, you could help me with an issue with the background color of the presenting view controller. 
On iPhone devices the background color will change to black on portrait orientation. On landscape, the color is correct. On iPad it works well in both orientations.

kind regards

**Comment by CooperRS** [comment]
Hi there!

Which background color do you mean? Do you mean the background color of RMActionController? Can you send me a screencast of the problem? I'm not sure if I good it right :/.

Best regards,
Roland

**Comment by bender75** [comment]
Hello Roland,

thank you very much. Please see attached screencasts

[screencasts.zip](https://github.com/CooperRS/RMActionController/files/955048/screencasts.zip)

**Comment by CooperRS** [comment]
Hey!

How do you present the `RMActionController`? From code or from XIB? And do you set the `modalPresentationStyle` somewhere?

This usually happens, when the `modalPresentationStyle` is not set to `.Custom` or `.OverCurrentContext` or something similar (see [here](https://github.com/CooperRS/RMActionController/blob/master/RMActionController/RMActionController.m#L132) for where `RMActionController`sets its values).

Best regards,
Roland
