### ISSUE TITLE
is there a way to use the blurred action sheets without any view?

### ISSUE THREAD

**Issue by Sebacho-Barajas** [CooperRS/RMActionController#24]
is there a way to use the blurred action sheets without any view?

this is an example of what I'm asking for :
![img_7887](https://cloud.githubusercontent.com/assets/10381993/24320002/3f8216a4-1102-11e7-8fc8-232d197628ed.jpg)

**Comment by CooperRS** [comment]
Hi there!

I disallowed empty view because I thought in this use case you should use the Apple provided `UIAlertController`. However, I think `UIAlertController` does not have a black style, right?

Best regards,
Roland
