### ISSUE TITLE
Is there a way to have sharp corners instead of rounded ones?

### ISSUE THREAD

**Issue by slobodanantonijevic** [CooperRS/RMActionController#27]
Love the library, but I have a project where I need flat design with sharp corners and no border width (padding) are there any properties that I am missing to achieve this?

Cheers

**Comment by CooperRS** [comment]
Hi there!,

Right now this is not possible. But it should be easy to implement. Take a look at [-[RMActionController setupContainerElements]](https://github.com/CooperRS/RMActionController/blob/master/RMActionController/RMActionController.m#L248). In line 248 and 258 the corner radius is set. In addition, in [-[RMActionController setupConstraints]](https://github.com/CooperRS/RMActionController/blob/master/RMActionController/RMActionController.m#L287) the padding is set up. You just need to change these values to 0 and you are done.

Feel free to make a PR out of it! 😃
