### ISSUE TITLE
The action sheet goes over the device height when the device is in landscape

### ISSUE THREAD

**Issue by pablocarmu** [CooperRS/RMActionController#28]
Hi!,
When the device, in this case an iphone, is in landscape orientation and you presents a RMActionController with many actions, the action sheet goes over the height of the device and then some actions are hidden.

Here is a simple example:
![img_0604](https://user-images.githubusercontent.com/8929738/29616449-ddf55e6e-8811-11e7-859a-d7f930578f69.PNG)

Is there a way to do scrollable the actions view or any way to solve this issue?
Thanks.

**Comment by CooperRS** [comment]
Yep, this is indeed an issue. Currently, there is no way to make this thing scrollable. Howeerv, this should be implemented. PR?
